### ISSUE TITLE
Does it support (or will support) gradle, kotlin,... etc. ？

### ISSUE THREAD

**Issue by ghost** [lhwdev/ASM#11]

**Comment by lhwdev** [comment]
Hmm.. Yes, we will!
We're developing gradle build system, (by @GonngBJ ) (but he is trying developing gradle)
and I believe it'll be AMAZING.
If gradle is supported, kotlin and others will be supported.
(But they are in progress)
However I think ASM will be the powerful mobile IDE.

Thanks for paying attention to our repository, @MikaGuraNTK ! :heart:

**Comment by yhs0602** [comment]
@lhwdev supporting Kotlin will be hard! Good luck and I hope to see it! There's no Kotlin IDE yet. I am expecting to see it, cheers!

**Comment by lhwdev** [comment]
@KYHSGeekCode Hmm kotlin..? However it's hard work. I'll try supporting ALL features like AS(android studio)

+sorry for late reply, i'm in exam period ~~(grammer?Which is eaten for lunch?)~~
~~++both us are korean?~~

**Comment by yhs0602** [comment]
I wish you luck with your final exam! Actually I am in final exam period too, but 3rd grade-2nd semester-Final. Are you in 3rd grade? If not, you're a quite hard-studier!👍

**Comment by lhwdev** [comment]
@KYHSGeekCode Am I?? (I'm middle school, 2nd grade; Actually, some of our asm-team's members are)
However thanks you!
I wish you luck too! :+1:
