### ISSUE TITLE
MainActivity.java Bug

### ISSUE THREAD

**Issue by artiren012** [lhwdev/ASM#8]
in xml-editor, MainActivity.java code is wrong. can you find bug..?

**Comment by lhwdev** [comment]
Oops, I didn't know that you made issue.
I'll see it.

**Comment by lhwdev** [comment]
I adjusted a little bit.
@AppMagnesium 

However, good issue! When you donno how to resolve, do like this.
Also, when you want to merge it to master, make a pull request.

Hmm.. This branch has many things to fix.

**Comment by lhwdev** [comment]
@AppMagnesium 계세요..?

**Comment by artiren012** [comment]
@lhwdev 네

**Comment by lhwdev** [comment]
This repository _isn't now maintained_ in this repository, and this will hold only modules related to the Plugin API.
> to @appmagnesium: you can issue the same in our new repo.
